In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Ler dataset

df = pd.read_csv('Dataset_cleared.csv')

Preparar o dataset

In [3]:
#Passar valores contínuos para valores discretos da label


In [4]:
#Fica assim
df

original_shape_Flatness  original_shape_LeastAxisLength  \
0                    0.219031                        5.542891   
1                    0.215045                        5.209030   
2                    0.289526                        1.632763   
3                    0.216692                        6.435946   
4                    0.595806                        7.374952   
...                       ...                             ...   
2646                 0.375133                        4.534490   
2647                 0.687954                        8.589183   
2648                 0.185778                        2.586515   
2649                 0.247844                        2.471175   
2650                 0.273192                       11.674262   

      original_shape_MajorAxisLength  original_shape_Maximum2DDiameterColumn  \
0                          25.306411                               24.020824   
1                          24.222923                               30.016662   
2                           5.639429                                6.000000   
3                          29.700850                               37.054015   
4                          12.378110                               15.524175   
...                              ...                                     ...   
2646                       12.087678                               12.806248   
2647                       12.485120                               14.422205   
2648                       13.922612                               11.045361   
2649                        9.970706                                7.280110   
2650                       42.732887                               49.040799   

      original_shape_Maximum2DDiameterRow  \
0                               39.051248   
1                               31.064449   
2                                6.324555   
3                               43.566042   
4                               14.142136   
...                                   ...   
2646                            11.401754   
2647                            14.317821   
2648                            14.866069   
2649                             7.211103   
2650                            50.219518   

      original_shape_Maximum2DDiameterSlice  original_shape_Maximum3DDiameter  \
0                                 26.000000                         41.509035   
1                                 23.021729                         31.064449   
2                                  5.099020                          6.324555   
3                                 35.227830                         49.284886   
4                                 12.041595                         15.588457   
...                                     ...                               ...   
2646                              13.928388                         14.628739   
2647                              12.649111                         15.165751   
2648                              12.165525                         15.842980   
2649                               7.615773                         10.440307   
2650                              46.097722                         51.048996   

      original_shape_MeshVolume  original_shape_MinorAxisLength  \
0                   1874.625000                       21.474857   
1                   1717.416667                       20.477091   
2                     29.291667                        4.958806   
3                   3610.791667                       28.419506   
4                    506.541667                        9.653513   
...                         ...                             ...   
2646                 313.083333                        9.595771   
2647                 605.541667                        9.416961   
2648                 177.541667                        7.855304   
2649                  70.041667                        4.521458   
2650         

In [35]:
X = df.loc[:, df.columns != 'Malignancy']
Y = df['Malignancy']

In [36]:
#Training set e Test set

from sklearn.model_selection import train_test_split

X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.20)

In [37]:
#Fit classifier in Training set

#kernel (distrib nao linear): poly, rbf, sigmoid
#kernel (distrib linear): linear
#kernel (matriz de similaridade como input): precompute
#também se pode especificar um kernel personalizado fornecendo uma função chamável (callable) que implementa o cálculo do kernel desejado

#poly : passa os dados 1D para 2D quando temos distribuição nao linear, passando a ter distribuição linear em 2D
#default kernel = 'rbf'

from sklearn.svm import SVC

classifier = SVC(kernel = 'rbf')
SVM_fit = classifier.fit(X_Train, Y_Train)

In [38]:
# Predicting the test set results

SVM_pred = classifier.predict(X_Test)

In [39]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, SVM_pred)
print(cm)

[[  0   0  41   8   0]
 [  0   0 152   8   1]
 [  1   0 196  16   4]
 [  0   0  68  22   1]
 [  0   0   3  10   0]]


In [40]:
from sklearn.metrics import accuracy_score

print("Precisão do SVM: ", accuracy_score(Y_Test, SVM_pred))

Precisão do SVM:  0.4105461393596987
